#------------------------------------------------
# Makefile to clean pgfplot externalized graphs
#------------------------------------------------

# Nothing to do by default (handled by pgfplot)
all:
	@echo

clean:
	rm -f *.dep *.dpth *.glo *.ist *.log *.pdf

clean_all: clean